name: Mirror to Gitlab

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
      with:
        path: ./github
    
    - name: Copy to glitch dir
      run: | 
        mkdir glitch
        rsync -ahvr --progress ./github/ ./glitch --exclude '.git/'

    - name: Change config
      run: | 
        cd ./glitch
        cp ./.env.sample ./.env
        sed -i -e "s/SCHEME=https/SCHEME=http/g" ./.env
        sed -i -e "s/HOSTNAME=localhost/HOSTNAME=fido2-glitch.s1r-j.tk/g" ./.env
        sed -i -e "s/PRIV_KEY=.\/ssl\/localhost-key.pem/PRIV_KEY=/g" ./.env
        sed -i -e "s/CERT=.\/ssl\/localhost.pem/CERT=/g" ./.env
        sed -i -e "s/LOG_LEVEL=info/LOG_LEVEL=warn/g" ./.env
        sed -i -e "s/DB_RESET=/DB_RESET=* 59 23 * * */g" ./.env
        sed -i -e "s/LOG_ROTATE=/LOG_ROTATE=* 59 23 * * */g" ./.env
        sed -i -e "s/\.env/#\.env/g" ./.gitignore

    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@main
      with:
        project-id: '${{ secrets.PROJECT_ID }}'
        auth-token: '${{ secrets.AUTH_TOKEN }}'
